# Generated by Django 3.0.5 on 2020-04-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('msg', models.CharField(choices=[('issue', 'Issue'), ('other', 'Other')], max_length=10)),
                ('content', models.TextField()),
            ],
        ),
    ]
