# Generated by Django 3.0.5 on 2020-04-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_contact_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='msg',
        ),
    ]
