# Generated by Django 3.0.5 on 2020-04-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0004_auto_20200413_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=400),
        ),
    ]
